export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR'
export const ERROR = 'ERROR'
export const LOADING = 'LOADING'
export const LOGGEDIN = 'LOGGEDIN'
