require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'

target 'BookAppointment' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'BookAppointmentTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'BookAppointment-tvOS' do
  # Pods for BookAppointment-tvOS

  target 'BookAppointment-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
